version: 2.1
jobs:
  MySQL:
    docker:
      - image: circleci/mysql:8.0.21
        environment:
          # MYSQL_ROOT_PASSWORD: ''
          # MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: stocks
          MYSQL_USER: monty
          MYSQL_PASSWORD: some_pass
    steps:
     - run:
        name: Wait for Database Connection
        # preinstalled in circleci/* docker image
        command: dockerize -wait tcp://localhost:3306 -timeout 1m
     - run: echo "I hope this works"
  Java:
    docker:
      - image: 'circleci/openjdk:latest' # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello cruel world" # run the `echo` command 
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/my-reports
workflows:
 version: 2
 build-deploy:
   jobs:
     - MySQL
     - Java:
         requires:
           - MySQL
