version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:latest' # the primary container, where your job's commands are run
      - image: circleci/mysql:8.0.21
        environment:
          # MYSQL_ROOT_PASSWORD: ''
          # MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: stocks
          MYSQL_USER: monty
          MYSQL_PASSWORD: some_pass      
    steps:
      - checkout # check out the code in the project directory
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 20
            done
            echo Failed waiting for MySQL && exit 1      
      - run: echo "hello cruel world" # run the `echo` command 
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/my-reports
