version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:latest' # the primary container, where your job's commands are run
      - image: 'circleci/mysql:8.0.21'
        environment:
          MYSQL_ROOT_PASSWORD: Rynomite@83
          MYSQL_DATABASE: stocks
          MYSQL_USER: monty
          MYSQL_PASSWORD: some_pass
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello cruel world" # run the `echo` command 
      - run: mysql -u monty -p
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/my-reports
